### ISSUE TITLE
Facebook Login with Custom Auth Provider doesn't trigger Callback.

### ISSUE THREAD

**Issue by ibalejandro** [auth0/Lock-Facebook.Android#16]
I am trying to use Lock-Facebook for Android and I was able to make it work but when I try to use the Facebook SDK to avoid opening a web view and entering the credentials again, I don't receive any Callback on my app.

However, when I use it without Custom Auth Providers (_.withAuthHandlers()_) the Callback is triggered and it works, but this is not the desired behaviour.

This is how I'm trying to achieve it:

```java
@Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    FacebookSdk.sdkInitialize(getApplicationContext());
    AppEventsLogger.activateApp(getApplication());
    String clientId = getApplicationContext().getResources().getString(R.string.auth0_client_id);
    String domain = getApplicationContext().getResources().getString(R.string.auth0_domain);
    Auth0 auth0 = new Auth0(clientId, domain);
    apiClient = new AuthenticationAPIClient(auth0);
    FacebookAuthProvider provider = new FacebookAuthProvider(apiClient);
    provider.setPermissions(Arrays.asList("public_profile", "email"));
    FacebookAuthHandler handler = new FacebookAuthHandler(provider);
    
    lock = Lock.newBuilder(auth0, callback)
        .withAuthHandlers(handler)
        .build(this);

    startActivity(lock.newIntent(this));
  }

  private LockCallback callback = new AuthenticationCallback() {
    @Override
    public void onAuthentication(Credentials credentials) {
      Toast.makeText(getApplicationContext(), "Authenticated", Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onCanceled() {
      Toast.makeText(getApplicationContext(), "Canceled", Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onError(LockException error) {
      Toast.makeText(getApplicationContext(), "Authentication error", Toast.LENGTH_SHORT).show();
    }
  };
```
 
Thanks in advance for your help.

**Comment by lbalmaceda** [comment]
Hi @ibalejandro 
Facebook SDK doesn't allow the users to customize the `requestCode` parameter once the SDK is initialized, so in that case they use a default code. As the provider itself handles the Facebook SDK initialization you don't need to call `initialize` in your code. But _if you have_, then the provider can't set its own request code and the callback won't be triggered.  Remove the `FacebookSdk.sdkInitialize(getApplicationContext());` line and it should work. If it doesn't, kill the activity as the sdk may still be initialized from a previous run.

There's a log which tell you if this is the case https://github.com/auth0/Lock-Facebook.Android/blob/4713e8826f4ed9828e077f89a966a56b487cad98/lock-facebook/src/main/java/com/auth0/android/facebook/FacebookApi.java#L25-L27

Cheers.

**Comment by ibalejandro** [comment]
Thank you very much @lbalmaceda. I followed your suggestion and it worked! :+1:

**Comment by blurrcat** [comment]
@ibalejandro What if I need to call `sdkInitialize` before creating the lock? What should the request code be?
For example, I need to use the facebook event API in other activities, even before the user is logged in.

**Comment by lbalmaceda** [comment]
@blurrcat FacebookSdk will set a default code if it's initialized without one, but there's no way to tell it to use the one Lock is expecting. Since a few months they no longer accept setting a custom `request_code` so I added this PR to handle that case. https://github.com/auth0/Lock-Facebook.Android/pull/18
I hope it helps. Cheers
