### ISSUE TITLE
Setting audience by withAuthenticationParameters configuration option doesnt return JWT access token

### ISSUE THREAD

**Issue by rushi216** [auth0/Lock-Facebook.Android#20]
I have setup "audience" parameter by using withAuthenticationParameter configuration, but it still doesnt return JWT access_token as expected. It only returns Cw**XmS***m8TF_g like token.

**Comment by lbalmaceda** [comment]
@rushi216 
On your `Auth0` instance call `setOIDCConformant(true)` before creating the provider.

```java
Auth0 auth0 = new Auth0("clientId", "domain");
auth0.setOIDCConformant(true); //Must be set to true to request audience
AuthenticationAPIClient client = new AuthenticationAPIClient(auth0);
provider = new FacebookAuthProvider(client);
```
