### ISSUE TITLE
Facebook login issue using native sdk with auth 0

### ISSUE THREAD

**Issue by GrishmaPromact** [auth0/Lock-Facebook.Android#21]
I refer this link for login with with facebook in android using native sdk. I followed all steps explain in this git hub project.I use simple Activity to login with facebook without lock.I attached that activity and facebookAuthProvider.java file. I am not able to login with facebook and got error like this:
Failed to login with facebook
An error occurred when trying to authenticate with the server.
Please help me to solve this issue.
Thanks.

**Comment by lbalmaceda** [comment]
Hi @GrishmaPromact,
If your Auth0 Client has been created after June 8th you won't be able to use this extension as the endpoint used to obtain the auth0 access token [is disabled](https://auth0.com/docs/api/authentication#social-with-provider-s-access-token). Using a browser to perform authentication is the recommended way. You can do that using [auth0.android's](https://github.com/auth0/auth0.android#authentication-with-hosted-login-page) `WebAuthProvider` class. I'll add a note to both this and Google's extension repos to warn the users.
Cheers,

**Comment by ShreyashPromact** [comment]
@lbalmaceda 
That means, we can't do login using Facebook native SDK? I mean to log in with Auth0 but without Lock.
Can you please confirm on this?

Thanks.

Sincerely,
Shreyash

**Comment by lbalmaceda** [comment]
Yes, that's also true: Logging in with just "Facebook SDK" (no auth0 at all) it's fine, you get your "facebook access_token". But then you'd need to exchange it with auth0 by calling that no-longer-available endpoint in order to get the "auth0 access_token", and that's where it will fail.
Cheers

**Comment by ShreyashPromact** [comment]
@lbalmaceda 
Thanks for your reply.  :)
