### ISSUE TITLE
Error login with facebook

### ISSUE THREAD

**Issue by mauriciocoelho** [auth0/Lock-Facebook.Android#4]
I'm with the following problem to log in, it would be some configuration on facebook or a problem with the lock?
Would you help me?

![screenshot_2015-08-04-14-16-29](https://cloud.githubusercontent.com/assets/5712300/9067598/c47aa6e4-3ab4-11e5-9f83-46263225ffba.png)
![screenshot_2015-08-04-14-16-37](https://cloud.githubusercontent.com/assets/5712300/9067600/c48e1b0c-3ab4-11e5-815a-576764f57fc2.png)

**Comment by hzalaz** [comment]
You are probably missing registering the keystore hash with FB (at least the debug one) and that's why FB is asking you to register it in the second screenshot, check the FB quick start guide https://developers.facebook.com/docs/android/getting-started#create_hash

**Comment by mauriciocoelho** [comment]
I had already done it, I forgot to mention, but that is "sometimes"

**Comment by hzalaz** [comment]
Closing this one, please reopen if needed
